# Generated by Django 3.2.1 on 2021-05-05 07:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Druh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oznaceni_druhu', models.CharField(help_text='Zadejte text o maximální délce 50 znaků; text musí být jedinečný', max_length=50, unique=True, verbose_name='Označení druhu auta')),
                ('karoserie', models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('kombi', 'Kombi'), ('liftback', 'Liftback'), ('suv', 'SUV'), ('kabriolet', 'Kabriolet')], default='sedan', help_text='Vyberte karoserii', max_length=20, verbose_name='Karoserie')),
            ],
            options={
                'verbose_name': 'Druh auta',
                'verbose_name_plural': 'Druh auta',
                'ordering': ['oznaceni_druhu'],
            },
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte text o maximální délce 100 znaků', max_length=100, verbose_name='Název auta')),
                ('popis', models.TextField(blank=True, null=True, verbose_name='Popis auta')),
                ('cena', models.FloatField(help_text='Zadejte nezáporné desetinné číslo', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cena')),
                ('stav', models.IntegerField(blank=True, choices=[(4, 'jako nové'), (3, 'málo ojeté'), (2, 'často jeté'), (1, 'hodně ojeté')], default=3, help_text='Vyberte označení stavu', max_length=1, verbose_name='Stav auta')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='zbozi/%Y/%m/%d/', verbose_name='Fotka auta')),
                ('druh', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bazar.druh')),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Auto',
                'ordering': ['-cena', 'nazev'],
            },
        ),
    ]
