# Generated by Django 3.2.1 on 2021-05-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='stav',
            field=models.IntegerField(blank=True, choices=[(4, 'jako nové'), (3, 'málo ojeté'), (2, 'často jeté'), (1, 'hodně ojeté')], default=3, help_text='Vyberte označení stavu', verbose_name='Stav auta'),
        ),
    ]
