# Generated by Django 3.2.1 on 2021-05-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0003_rename_karoserie_druh_oblast'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='ojete',
            field=models.CharField(blank=True, choices=[('ano', 'Ano'), ('ne', 'Ne')], default='ano', help_text='Vyberte, zda je auto ojete', max_length=20, verbose_name='Ojetina'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='stav',
            field=models.IntegerField(blank=True, choices=[(4, 'jako nové'), (3, 'málo ojeté'), (2, 'často jeté'), (1, 'hodně ojeté')], default=3, help_text='Vyberte označení stavu', verbose_name='Sta0v auta'),
        ),
        migrations.AlterField(
            model_name='druh',
            name='oblast',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('kombi', 'Kombi'), ('liftback', 'Liftback'), ('suv', 'SUV'), ('kabriolet', 'Kabriolet'), ('kupé', 'Kupé')], default='sedan', help_text='Vyberte karoserii', max_length=20, verbose_name='Karoserie'),
        ),
    ]
