# Generated by Django 3.2.1 on 2021-05-05 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0004_auto_20210505_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='sila',
            field=models.FloatField(help_text='Zadej pocet konskych sil', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='hp'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='ojete',
            field=models.FloatField(help_text='Zadej pocet najetych kilometetru', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='kilometry'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='stav',
            field=models.IntegerField(blank=True, choices=[(5, 'nové'), (4, 'jako nové'), (3, 'málo ojeté'), (2, 'často jeté'), (1, 'hodně ojeté')], default=3, help_text='Vyberte označení stavu', verbose_name='Stav auta'),
        ),
    ]
