# Generated by Django 3.2.1 on 2021-05-05 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0006_auto_20210505_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='cena',
            field=models.IntegerField(help_text='Zadejte nezáporné desetinné číslo', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cena'),
        ),
    ]
