# Generated by Django 3.2.1 on 2021-05-05 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0007_alter_auto_cena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='ojete',
            field=models.IntegerField(help_text='Zadej pocet najetych kilometetru', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='kilometry'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='sila',
            field=models.IntegerField(help_text='Zadej pocet konskych sil', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Počet koní'),
        ),
    ]
